name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
 
permissions:
  contents: write
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false


 
jobs:
  update-wikilinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Convert Wikilinks
        run: cd content && find -type f -name "*.md" -exec sed -i -e 's/\.excalidraw/\.svg/g' {} +
       

  build:
    needs: update-wikilinks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update wikilinks to absolute paths'
          add: 'content/**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
